version: 2

sources:
  - name: jaffle_shop
    database: raw

    tables:
      - name: orders
        loaded_at_field: _etl_loaded_at
        freshness: # make this a little more strict
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}

      - name: customers
        columns:
          - name: id
            tests:
              - not_null
              - unique

  - name: stripe
    tables:
      - name: payment